version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: dbschema-postgres
    environment:
      POSTGRES_DB: dbschemastudio
      POSTGRES_USER: dbstudio
      POSTGRES_PASSWORD: dbstudio
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local
